In [2]:
import tensorflow as tf
import numpy as np
#

In [9]:
rank_2_tensor = tf.constant([[10, 7],[1,5],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([3, 2]), 2)

In [42]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([3, 2, 5]), 3)

In [11]:
np.array(rank_2_tensor)

array([[10,  7],
       [ 1,  5],
       [ 3,  4]], dtype=int32)

In [12]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
#

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [3]:
tf.convert_to_tensor([1,2,4,5,6])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 4, 5, 6], dtype=int32)>

In [6]:
tf.reduce_max([1,2,4,5,6])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [12]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
rank_4_tensor


<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [11]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [15]:
rank_1_tensor = tf.constant([1,2,3,6,7,9,12,20,23,25,40,12,34,56])
tf.argmax(rank_1_tensor)
rank_1_tensor[0].numpy()
rank_1_tensor[-1].numpy()

56

In [26]:
rank_1_tensor[::-1].numpy()

array([56, 34, 12, 40, 25, 23, 20, 12,  9,  7,  6,  3,  2,  1],
      dtype=int32)

In [33]:
rank_2_tensor = tf.constant([[10, 7],[1,5],
                             [3, 4]])
rank_2_tensor
rank_2_tensor[1:, :].numpy()

array([[1, 5],
       [3, 4]], dtype=int32)

In [56]:
reshape_rank_3_tensor=tf.reshape(rank_3_tensor, shape=(5,6))
tf.shape(reshape_rank_3_tensor)
reshape_rank_3_tensor

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]], dtype=int32)>

In [50]:
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [48]:
tf.shape(rank_3_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 5], dtype=int32)>